### ISSUE TITLE
Download from TestPyPI -> tests -> deploy to PyPI

### ISSUE THREAD

**Issue by ashwinvis** [snek5000/snek5000#166]
A manual workflow for this

Todo list:

1. [ ] release pymech
2. [ ] release fluidsim-core
3. [ ] release snek5000 0.8.0
4. [ ] release snek5000-phill, snek5000-cbox, snek5000-tgv (manual should be enough)

**Comment by paugier** [comment]
We have a manual workflow in snek5000-cbox (https://github.com/snek5000/snek5000-cbox/blob/main/.github/workflows/tests_slow.yml). Note that the button appears only when the workflow file is in main, i.e. not when the PR is created.  Just writing this here because I struggle a bit to make it work because I didn't know that!

We will have to think about the release process for snek5000-phill, snek5000-cbox, snek5000-tgv... I guess we will need another snek5000 release candidate with all our work before uploading phill, cbox and tgv on PyPI.

**Comment by paugier** [comment]
Actually, it would be better to release the first official versions of snek5000-phill, snek5000-cbox, snek5000-tgv after snek5000 0.8.0...
