### ISSUE TITLE
Documentation build should fail if the execution of a notebook fails

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000#188]
It's too easy to break the documentation without noticing it...

**Comment by ashwinvis** [comment]
Toggle all to True?

Name | Type | Default | Description
-- | -- | -- | --
nb_execution_allow_errors | bool | False | Allow errors during execution
nb_execution_raise_on_error | bool | False | Raise an exception on failed execution, rather than emitting a warning
nb_execution_show_tb | bool | False | Print traceback to stderr on execution error

https://myst-nb.readthedocs.io/en/latest/configuration.html

**Comment by ashwinvis** [comment]
Except allow errors, of course.

**Comment by paugier** [comment]
Done in https://github.com/snek5000/snek5000/pull/190
